# Generated by Django 2.1.4 on 2018-12-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181206_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='twittedID',
            new_name='twitterID',
        ),
    ]
