# Generated by Django 2.1.4 on 2018-12-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181206_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instapost',
            name='link',
        ),
        migrations.RemoveField(
            model_name='twitterpost',
            name='link',
        ),
        migrations.AddField(
            model_name='instapost',
            name='created_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selfpost',
            name='created_at',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='created_at',
            field=models.IntegerField(default=0),
        ),
    ]
