# Generated by Django 2.1.4 on 2018-12-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181206_0716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='user',
        ),
    ]
