# Generated by Django 2.1.4 on 2018-12-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181206_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instapost',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='selfpost',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='twitterpost',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
